pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/jcenter'}
        maven { url 'https://maven.aliyun.com/repository/google'}
        maven {url 'https://maven.aliyun.com/repository/gradle-plugin'}
        maven {//佳博打印机
            url  "http://118.31.6.84:8081/repository/maven-public/"
            allowInsecureProtocol true
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url "https://jitpack.io" }
        google()
        jcenter()
        maven { url 'https://maven.aliyun.com/repository/jcenter'}
        maven { url 'https://maven.aliyun.com/repository/google'}
        maven {url 'https://maven.aliyun.com/repository/gradle-plugin'}
        maven {//佳博打印机
            url  "http://118.31.6.84:8081/repository/maven-public/"
            allowInsecureProtocol true
        }
    }
}
rootProject.name = "PrintSDK"
include ':app'
include ':sdktool'
